routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Corporativas
Route::get('/', 'Corporativa\FrontendController@home')->name('corporativa.home');

Route::get('/test', function () {
    return view('corporativa/home');
})->name('corporativa.test');

Route::as('corporativa.')
    ->prefix('libertad')
    ->group(
        function () {
            Route::get('acerca-de', 'Corporativa\FrontendController@acerca_de')->name('acerca_de');
            Route::get('contacto', 'Corporativa\FrontendController@contacto')->name('contacto');
            Route::get('libreria', 'Corporativa\FrontendController@libreria')->name('libreria');
            Route::get('instituciones', 'Corporativa\FrontendController@instituciones')->name('instituciones');
        }
    );

// Aplicacion
Route::as('app.')
    ->prefix('app')
    ->group(
        function () {
            Route::get('/', 'Aplicacion\FrontendController@dashboard')->name('dashboard');
            Route::get('mis-suscripciones', 'Aplicacion\FrontendController@mis_suscripciones')->name('representante-suscripciones');
            Route::get('listado-de-tareas', 'Aplicacion\FrontendController@listado_tareas')->name('representante-tareas');
            Route::get('listado-de-tests', 'Aplicacion\FrontendController@listado_tests')->name('representante-tests');

            /**
             * Rutas para desarrollar los libros por el usuario
             */
            Route::get('libros', 'Aplicacion\FrontendController@listado_libros')->name('libros');
            Route::get('/archivo/{segmentoLibro}/revista', 'Aplicacion\LibroController@revista_archivo')->name('archivo.revista');
            Route::get('/archivo/{segmentoLibro}/download', 'Aplicacion\LibroController@downloadSegmentoLibro')->name('archivo.download');
//            Route::get('/tarea/{tarea}/desarrollo', 'Aplicacion\LibroController@desarrolloTarea')->name('tarea.desarrollo');
            Route::get('/test/{test}/desarrollo', 'Aplicacion\LibroController@desarrolloTest')->name('test.desarrollo');

            /**
             * Desarrollo de Tareas
             */
            Route::get('/desarrollo/{material_estudiante}', 'Aplicacion\DesarrolloController@index')
                ->name('desarrollo.index')
                ->middleware('auth');
            Route::get('/desarrollo/{material_estudiante}/{tarea}', 'Aplicacion\DesarrolloController@tarea')
                ->name('desarrollo.tarea')
                ->middleware('auth');
            Route::post('/desarrollo/{materialEstudiante}', 'Aplicacion\DesarrolloController@store')
                ->name('desarrollo.store')
                ->middleware('auth');

            /**
             * Rutas para administrar el perfil del usuario
             */
            Route::get('/user/perfil', 'Aplicacion\UserController@perfil')->name('user.perfil');
            Route::post('/user/perfil/{user}/store', 'Aplicacion\UserController@storePerfil')->name('user.perfil.store');
            Route::post('/user/perfil/{user}/store_rol_user', 'Aplicacion\UserController@storeRolUser')->name('user.rol_user.store');
            Route::delete('/user/perfil/destroy_rol_user/{rolesUsers}', 'Aplicacion\UserController@destroyRol')->name('user.rol_user.destroy');

            /**
             * Rutas para registrar los libros por el usuario
             */
            Route::resource('material-estudiante', 'Aplicacion\MaterialEstudianteController');

            /**
             * Registrar docente
             */
            Route::resource('docente', 'Aplicacion\DocenteController');
            Route::get('/docente/estudiante/detalle', 'Aplicacion\DocenteController@detalleEstudiantesAprobar')->name('docente.estudiante.index');
            Route::get('/docente/estudiante/aprobar/{estudiante}', 'Aplicacion\DocenteController@aprobarEstudiante')->name('docente.estudiante.aprobar');
            Route::get('/docente/estudiante/cancelar/{estudiante}', 'Aplicacion\DocenteController@cancelarEstudiante')->name('docente.estudiante.cancelar');
            Route::get('/docente/representante/aprobar/{representante_estudiante}', 'Aplicacion\DocenteController@aprobarRepresentante')->name('docente.representante.aprobar');
            Route::resource('material-docente', 'Aplicacion\MaterialDocenteController');

            /**
             * Registrar estudiante
             */
            Route::resource('estudiante', 'Aplicacion\EstudianteController');

            /**
             * Representante
             */
            Route::resource('representante-estudiante', 'Aplicacion\RepresentanteEstudianteController');
            Route::post('representante-estudiante/asignar', 'Aplicacion\RepresentanteEstudianteController@asignarEstudianteRepresentante')->name('representante-estudiante.asignar');
            Route::get('representante-estudiante/cambiar/{user}', 'Aplicacion\RepresentanteEstudianteController@cambiarUsuarioEstudiante')->name('representante-estudiante.cambiar');

            /**
             * Calificar tareas
             */
            Route::resource('tarea', 'Aplicacion\TareaController');
            Route::get('tarea/calificar/{materialDocente}', 'Aplicacion\TareaController@calificar')->name('tarea.calificar');
            Route::get('tarea/calificar/{materialDocente}/{segmentoLibro}', 'Aplicacion\TareaController@calificar')
                ->name('tarea.calificar.segmento');
            Route::get('tarea/calificar/{materialDocente}/tarea/{tarea}', 'Aplicacion\TareaController@calificarTarea')
                ->name('tarea.calificar.tarea');

            Route::post('tarea/{materialEstudiante}/{desarrollo}', 'Aplicacion\TareaController@store')->name('tarea.calificar.store');

//            Route::get('detalle-registro-libro', 'Aplicacion\EstudianteController@detalleRegistroLibro')->name('estudiante.detalle-registro-libro');
//            Route::get('registrar-libro', 'Aplicacion\EstudianteController@registroLibro')->name('estudiante.registrar-libro');

//            Route::get('instituciones', 'Aplicacion\InstitucionController@index')->name('institucion.index');
//            Route::get('/institucion/create', 'Aplicacion\InstitucionController@create')->name('institucion.create');
//            Route::post('/institucion/store', 'Aplicacion\InstitucionController@store')->name('institucion.store');
//            Route::delete('/institucion/destroy/{estudiante}', 'Aplicacion\InstitucionController@destroy')->name('institucion.destroy');
        }
    );

// Adminitrator
Route::get('/admin', 'HomeController@index')
    ->name('admin.home');

Route::as('admin.')
    ->prefix('admin')
    ->group(
        function () {
            Route::resource('abreviatura', 'AbreviaturaController');
            Route::resource('asignatura', 'AsignaturaController');
            Route::resource('anio-lectivo', 'AnioLectivoController');
            Route::resource('institucion', 'InstitucionController');
            Route::resource('libro', 'LibroController');
            Route::resource('curso', 'CursoController');
            Route::resource('aula', 'AulaController');

            Route::resource('segmento_libro', 'SegmentoLibroController');
            Route::get('/segmento_libro/{libro}/index', 'SegmentoLibroController@index')->name('segmento_libro.index');
            Route::post('/segmento_libro/{libro}/store', 'SegmentoLibroController@store')->name('segmento_libro.store');

            Route::resource('tarea', 'TareaController');
            Route::get('/tarea/{segmentoLibro}/index', 'TareaController@index')->name('tarea.index');
            Route::post('/tarea/{segmentoLibro}/store', 'TareaController@store')->name('tarea.store');

            Route::resource('desarrollo', 'DesarrolloController');
            Route::get('/desarrollo/{tarea}/index', 'DesarrolloController@index')->name('desarrollo.index');
            Route::post('/desarrollo/{tarea}/store', 'DesarrolloController@store')->name('desarrollo.store');

            Route::resource('respuesta-desarrollo', 'RespuestaDesarrolloController');
            Route::post('/respuesta-desarrollo/{desarrollo}/store', 'RespuestaDesarrolloController@store')->name('respuesta-desarrollo.store');

            Route::resource('test', 'TestController');
            Route::get('/test/{segmentoLibro}/index', 'TestController@index')->name('test.index');
            Route::post('/test/{segmentoLibro}/store', 'TestController@store')->name('test.store');

            Route::resource('pregunta-desarrollo', 'PreguntaDesarrolloController');
            Route::get('/pregunta-desarrollo/{test}/index', 'PreguntaDesarrolloController@index')->name('pregunta-desarrollo.index');
            Route::post('/pregunta-desarrollo/{test}/store', 'PreguntaDesarrolloController@store')->name('pregunta-desarrollo.store');

            Route::resource('opcion-pregunta-desarrollo', 'OpcionPreguntaDesarrolloController');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/create', 'OpcionPreguntaDesarrolloController@create')->name('opcion-pregunta-desarrollo.create');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/index', 'OpcionPreguntaDesarrolloController@index')->name('opcion-pregunta-desarrollo.index');
            Route::post('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/store.imagen', 'OpcionPreguntaDesarrolloController@storeImagen')->name('opcion-pregunta-desarrollo.store.imagen');

app/Http/Controllers/Api/LibroController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Docente;
use App\Models\Estudiante;
use App\Models\Libro;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    public static function libroSelect2(Request $request)
    {
        $data = [];
        Libro::$search = $request->search;
        $libros = Libro::obtenerLibroAll() ?? [];

        foreach ($libros as $libro) {
            $data[] = ['id' => $libro->id, 'text' => "{$libro->titulo} ({$libro->curso->nombre})"];
        }

        return $data;
    }

    public static function libroDocenteSelect2(Docente $docente)
    {
        $data = [];
        $libros = Libro::obtenerLibroCursoAll($docente->aula->curso_id) ?? [];

        foreach ($libros as $libro) {
            $data[] = ['id' => $libro->id, 'text' => "{$libro->titulo} ({$libro->curso->nombre})"];
        }

        return $data;
    }

    public static function libroEstudianteSelect2(Estudiante $estudiante)
    {
        $data = [];
        $libros = Libro::obtenerLibroCursoAll($estudiante->aula->curso_id) ?? [];

        foreach ($libros as $libro) {
            $data[] = ['id' => $libro->id, 'text' => "{$libro->asignatura->nombre} / {$libro->titulo} ({$libro->curso->nombre})"];
        }

        return $data;
    }
}

app/Http/Controllers/Aplicacion/LibroController.php
<?php

namespace App\Http\Controllers\Aplicacion;

use App\Http\Controllers\Controller;
use App\Models\Archivo;
use App\Models\Libro;
use App\Models\OpcionPreguntaDesarrollo;
use App\Models\PreguntaDesarrollo;
use App\Models\SegmentoLibro;
use App\Models\Tarea;
use App\Models\Test;
use Illuminate\Http\Request;
use Storage;

class LibroController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', 'acceso-app']);
    }

//    public function revista(Libro $libro)
//    {
//        $segmentoLibros = SegmentoLibro::obtenerSegmentoLibroAll($libro->id);
//        $segmentoLibro = [];
//        return view('aplicacion.libro.index', compact('libro', 'segmentoLibros', 'segmentoLibro'));
//    }

    public function revista_archivo(SegmentoLibro $segmentoLibro)
    {
        $libro = $segmentoLibro->libro;
        $segmentoLibros = SegmentoLibro::obtenerSegmentoLibroAll($segmentoLibro->libro_id);

        return view('aplicacion.libro.revista_unidad', compact('segmentoLibro', 'segmentoLibros', 'libro'));
    }

    public function desarrolloTarea(Tarea $tarea)
    {
        return view('aplicacion.libro._desarrollo', compact('tarea'));
    }

    public function desarrolloTest(Test $test)
    {
        return view('aplicacion.test._desarrollo_test', compact('test'));
    }

    public static function opcionesPreguntas(Request $request = null, PreguntaDesarrollo $preguntaDesarrollo)
    {
        if ($preguntaDesarrollo->tipoPregunta->opciones) {
            $opcionesPregunta = OpcionPreguntaDesarrollo::obtenerOpcionPreguntaDesarrolloPreguntaDesarrolloAll($preguntaDesarrollo->id);
            switch ($preguntaDesarrollo->tipoPregunta->codigo) {
                case 'SELECCION':
                    return view('aplicacion.opcion_pregunta._seleccion', compact('opcionesPregunta'));
                    break;
                case 'IMAGEN':
                    return view('aplicacion.opcion_pregunta._imagen', compact('opcionesPregunta'));
                    break;

            }
        }

        switch ($preguntaDesarrollo->tipoPregunta->codigo) {
            case 'FRASE':
                return view('aplicacion.opcion_pregunta._frase', compact('preguntaDesarrollo'));
                break;
            default:
                return view('aplicacion.opcion_pregunta._texto', compact('preguntaDesarrollo'));
        }


    }

    public function downloadSegmentoLibro(SegmentoLibro $segmentoLibro)
    {
        if ($exists = Storage::disk('libros')->exists($segmentoLibro->documento)) {
            return Storage::disk('libros')->download($segmentoLibro->documento);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Archivos;
use App\Helpers\Helper;
use App\Http\Requests\Libro\StorePost;
use App\Http\Requests\Libro\UpdatePut;
use App\Models\Archivo;
use App\Models\Libro;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware(['auth', 'acceso-backend']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        Libro::$search = ($request->has('search')) ? request('search') : null;
        Libro::$paginate = 10;
        $libros = Libro::obtenerLibroPaginateAll();

        return view('backend.libro.index', ['libros' => $libros]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Libro();
        return view('backend.libro.create', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request)
    {
        $requestData = $request->validated();
        $validator = Validator::make($requestData, StorePost::myRules());

        if ($validator->fails()) {
            return redirect('admin.libro.create')
                ->withErrors($validator)
                ->withInput();
        }

        $requestData['anio_registro'] = date('Y');
        if ($model = Libro::create($requestData)) {
            if ($request->hasFile('portada')) {
                $model->portada = Archivos::storeImagen($request->titulo, $request->portada, 'portada_libro');
                $model->update();
            }

            return redirect()->route('admin.libro.index')->with('status', 'Libro creado con exito');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Libro $libro
     * @return \Illuminate\Http\Response
     */
    public function show(Libro $libro)
    {
        return view('backend.libro.show', ["model" => $libro]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Libro $libro
     * @return \Illuminate\Http\Response
     */
    public function edit(Libro $libro)
    {
        return view('backend.libro.edit', ["model" => $libro]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Libro $libro
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePut $request, Libro $libro)
    {
        if ($request->hasFile('portada')) {
            $libro->portada = Archivos::storeImagen($request->titulo, $request->portada, 'portada_libro');
        }

        $libro->update($request->validated());
        return back()->with('status', 'Libro actualizado con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Libro $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy(Libro $libro)
    {
        $libro->delete();
        return back()->with('status', 'Post eliminado con exito');
    }
}

resources/views/backend/libro/_form.blade.php
@csrf
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col col-8 text-aqua">
                <h6 class="m-0 font-weight-bold">libro</h6>
            </div>
        </div>

    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="form-group">
                    <label for="direccion" class="bmd-label-floating">Titulo</label>
                    <input class="form-control" type="text" name="titulo" id="titulo"
                           value="{{ old('titulo',$model->titulo) }}" required>

                    @error('titulo')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>
            <div class="col-sm-12 col-md-6">
                <label for="curso_id" class="bmd-label-floating">Curso</label>
                <select class="form-control select2" name="curso_id" id="curso_id"
                        data-ajax--url="{{route('api.curso.select2')}}" data-ajax--cache="true"
                        data-placeholder="Seleccionar..." required>
                    @if($model->curso_id)
                        <option value="{{$model->curso_id}}">{{$model->curso->nombre}}</option>
                    @endif
                </select>

                @error('curso_id')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>


        <div class="form-group">
            <div class="row mb-2">
                <div class="col-sm-12 col-md-6 py-2">
                    <label for="asignatura_id" class="bmd-label-floating">Asignatura</label>
                    <select class="form-control select2" name="asignatura_id" id="asignatura_id"
                            data-ajax--url="{{route('api.asignatura.select2')}}" data-ajax--data-type="json"
                            data-ajax--cache="true"
                            data-placeholder="Seleccionar..." required>
                        @if($model->asignatura_id)
                            <option value="{{$model->asignatura_id}}">{{$model->asignatura->nombre}}</option>
                        @endif
                    </select>

                    @error('asignatura_id')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="col-sm-12 col-md-6">
                    <label for="direccion" class="bmd-label-floating">Autor</label>
                    <input class="form-control" type="text" name="autor" id="autor"
                           value="{{ old('autor',$model->autor) }}" required>

                    @error('autor')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <label for="portada" class="bmd-label-floating">Portada</label>
                        {{--@include('includes.forms.file-input',['file_name'=>'portada', 'file_id'=>'portada', 'file_default'=>($model->portada) ? url('storage/portada_libro/'.$model->portada):null])--}}
                        <input type="file" class="dropify" name="portada" id="portada"
                               @if($model->portada) data-default-file="{{url('storage/portada_libro/'.$model->portada)}}" @endif>

                        @error('portada')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="col-sm-12 col-md-6">
                        <label for="direccion" class="bmd-label-floating">Editorial</label>
                        <input class="form-control" type="text" name="editorial" id="editorial"
                               value="{{ old('editorial',$model->editorial) }}" required>

                        @error('editorial')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
            </div>

            {{--<div class="form-group">--}}
            {{--<div class="row">--}}
            {{--<div class="col-12">--}}
            {{--<label for="portada" class="bmd-label-floating">Portada</label>--}}
            {{--@include('includes.forms.file-input',['file_name'=>'portada', 'file_id'=>'portada', 'file_default'=>($model->portada) ? url('storage/portada_libro/'.$model->portada):null])--}}
            {{--<input type="file" class="dropify" name="portada" id="portada"--}}
            {{--@if($model->portada) data-default-file="{{url('storage/portada_libro/'.$model->portada)}}" @endif>--}}

            {{--@error('portada')--}}
            {{--<small class="text-danger">{{ $message }}</small>--}}
            {{--@enderror--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}

            <div class="form-group">
                <div class="row">
                    <div class="col-12">
                        <label for="resumen" class="bmd-label-floating">Resumen</label>
                        <textarea class="form-control ckeditor-content" id="resumen" name="resumen">
                            {{$model->resumen}}
                        </textarea>

                        @error('resumen')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-12">
                        <label for="contenido" class="bmd-label-floating">Contenido</label>
                        <textarea class="form-control ckeditor-content" id="contenido" name="contenido">
                            {{$model->contenido}}
                        </textarea>

                        @error('contenido')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
            </div>


            <input type="hidden" id="token" value="{{ csrf_token() }}">

            <input type="submit" value="Enviar" class="btn btn-primary">

        </div>
    </div>
</div>

resources/views/backend/libro/create.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    {{ Breadcrumbs::render('admin.libro.create', $model ?? '') }}
@endsection

@section('content')
    @include('includes.validation-error-admin')
    <form class="needs-validation" action="{{ route("admin.libro.store") }}" method="POST" enctype='multipart/form-data'
          novalidate>
        @include('backend.libro._form')
    </form>
@endsection

resources/views/backend/libro/edit.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    {{ Breadcrumbs::render('admin.libro.create', $model ?? '') }}
@endsection

@section('content')
    @include('includes.validation-error-admin')
    <form action="{{ route("admin.libro.update",$model->id) }}" method="POST" enctype='multipart/form-data' novalidate>
        @method('PUT')
        @include('backend.libro._form')
    </form>
@endsection

resources/views/backend/libro/index.blade.php
@extends('layouts.aplicacion.app')

@section('content')
    @include('includes.forms.search-grid',['name_route'=>'admin.libro.index'])

    <div class="card">
        <div class="card-header card-header-primary">
            <div class="row">
                <div class="col col-9">
                    <h4 class="card-title">
                        Listado de Libros
                    </h4>
                    <div class="card-category">
                        Aqui encontrarás la parametrización de las Instituciones
                    </div>
                </div>
                <div class="col col-3 text-right">
                    <a class="btn btn-sm btn-success" href="{{ route('admin.libro.create') }}">
                        <i class="fe-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="table-responsive">

            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th style="width: 100px;">&nbsp;</th>
                    <th>Libro</th>
                    <th>Curso</th>
                    <th>Asignatura</th>
                    <th>Registro</th>
                    <th>
                        <small>Created_at</small>
                    </th>
                    <th>
                        <small>Updated_at</small>
                    </th>

                    <th class="text-center"><i class="fas fa-cogs"></i></th>
                </tr>
                </thead>
                <tbody>
                @foreach($libros as $libro)
                    <tr>
                        <td>
                            @if($libro->portada)
                                <img src="{{url('storage/portada_libro/'.$libro->portada)}}"
                                     alt="{{$libro->titulo}}" class="img-thumbnail" alt="{{$libro->portada}}">
                            @endif
                        </td>
                        <td class="py-3 align-middle">{{ $libro->titulo }}</td>
                        <td class="py-3 align-middle">{{ $libro->curso->nombre}}</td>
                        <td class="py-3 align-middle">{{ $libro->asignatura->nombre}}</td>
                        <td class="py-3 align-middle text-center">{{ $libro->anio_registro}}</td>
                        <td class="py-3 align-middle">
                            <small>{{ $libro->created_at->format('M d Y h:i') }}</small>
                        </td>
                        <td class="py-3 align-middle">
                            <div>
                                <small>{{ $libro->updated_at->format('M d Y h:i') }}</small>
                            </div>
                        </td>

                        <td class="py-3 align-middle text-center">
                            <a href="{{ route('admin.segmento_libro.index',$libro->id) }}"
                               class="nav-link-style mr-2 text-success" data-toggle="tooltip" data-placement="top"
                               title="ADMINISTRAR UNIDADES">
                                <i class="fe-upload"></i>
                            </a>

                            <a href="{{ route('admin.libro.show',$libro->id) }}"
                               class="nav-link-style mr-2" data-toggle="tooltip" data-placement="top"
                               title="REVISAR">
                                <i class="fe-eye"></i>
                            </a>

                            <a href="{{ route('admin.libro.edit',$libro->id) }}"
                               class="nav-link-style mr-2" data-toggle="tooltip" data-placement="top"
                               title="EDITAR">
                                <i class="fe-edit"></i>
                            </a>

                            <a href="" data-toggle="modal" data-target="#deleteModal" data-id="{{ $libro->id }}"
                               class="nav-link-style mr-2 text-danger" data-toggle="tooltip" data-placement="top"
                               title="ELIMINAR">
                                <i class="fe-trash-2"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="m-3">
                {{
                $libros
                    ->appends(['created_at' => request('created_at'),'search' => request('search'),])
                    ->links()
                }}
            </div>
        </div>
    </div>

    @include('includes.forms.modal-delete',['name_route'=>'admin.libro.destroy'])


@endsection

@section('scripts')
    <script type="text/javascript">
        window.deleteModalAjax('deleteModal', 'formDelete');
    </script>
@endsection

resources/views/backend/libro/show.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    {{ Breadcrumbs::render('admin.libro.create', $model ?? '') }}
@endsection

@section('content')
    <form id="form-view-libro">
        @include('backend.libro._form')
    </form>
@endsection

@section('scripts')
    <script type="text/javascript">
        window.disableInputForm('form-view-libro');
    </script>
@endsection