routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Corporativas
Route::get('/', 'Corporativa\FrontendController@home')->name('corporativa.home');

Route::get('/test', function () {
    return view('corporativa/home');
})->name('corporativa.test');

Route::as('corporativa.')
    ->prefix('libertad')
    ->group(
        function () {
            Route::get('acerca-de', 'Corporativa\FrontendController@acerca_de')->name('acerca_de');
            Route::get('contacto', 'Corporativa\FrontendController@contacto')->name('contacto');
            Route::get('libreria', 'Corporativa\FrontendController@libreria')->name('libreria');
            Route::get('instituciones', 'Corporativa\FrontendController@instituciones')->name('instituciones');
        }
    );

// Aplicacion
Route::as('app.')
    ->prefix('app')
    ->group(
        function () {
            Route::get('/', 'Aplicacion\FrontendController@dashboard')->name('dashboard');
            Route::get('mis-suscripciones', 'Aplicacion\FrontendController@mis_suscripciones')->name('representante-suscripciones');
            Route::get('listado-de-tareas', 'Aplicacion\FrontendController@listado_tareas')->name('representante-tareas');
            Route::get('listado-de-tests', 'Aplicacion\FrontendController@listado_tests')->name('representante-tests');

            /**
             * Rutas para desarrollar los libros por el usuario
             */
            Route::get('libros', 'Aplicacion\FrontendController@listado_libros')->name('libros');
            Route::get('/archivo/{segmentoLibro}/revista', 'Aplicacion\LibroController@revista_archivo')->name('archivo.revista');
            Route::get('/archivo/{segmentoLibro}/download', 'Aplicacion\LibroController@downloadSegmentoLibro')->name('archivo.download');
//            Route::get('/tarea/{tarea}/desarrollo', 'Aplicacion\LibroController@desarrolloTarea')->name('tarea.desarrollo');
            Route::get('/test/{test}/desarrollo', 'Aplicacion\LibroController@desarrolloTest')->name('test.desarrollo');

            /**
             * Desarrollo de Tareas
             */
            Route::get('/desarrollo/{material_estudiante}', 'Aplicacion\DesarrolloController@index')
                ->name('desarrollo.index')
                ->middleware('auth');
            Route::get('/desarrollo/{material_estudiante}/{tarea}', 'Aplicacion\DesarrolloController@tarea')
                ->name('desarrollo.tarea')
                ->middleware('auth');
            Route::post('/desarrollo/{materialEstudiante}', 'Aplicacion\DesarrolloController@store')
                ->name('desarrollo.store')
                ->middleware('auth');

            /**
             * Rutas para administrar el perfil del usuario
             */
            Route::get('/user/perfil', 'Aplicacion\UserController@perfil')->name('user.perfil');
            Route::post('/user/perfil/{user}/store', 'Aplicacion\UserController@storePerfil')->name('user.perfil.store');
            Route::post('/user/perfil/{user}/store_rol_user', 'Aplicacion\UserController@storeRolUser')->name('user.rol_user.store');
            Route::delete('/user/perfil/destroy_rol_user/{rolesUsers}', 'Aplicacion\UserController@destroyRol')->name('user.rol_user.destroy');

            /**
             * Rutas para registrar los libros por el usuario
             */
            Route::resource('material-estudiante', 'Aplicacion\MaterialEstudianteController');

            /**
             * Registrar docente
             */
            Route::resource('docente', 'Aplicacion\DocenteController');
            Route::get('/docente/estudiante/detalle', 'Aplicacion\DocenteController@detalleEstudiantesAprobar')->name('docente.estudiante.index');
            Route::get('/docente/estudiante/aprobar/{estudiante}', 'Aplicacion\DocenteController@aprobarEstudiante')->name('docente.estudiante.aprobar');
            Route::get('/docente/estudiante/cancelar/{estudiante}', 'Aplicacion\DocenteController@cancelarEstudiante')->name('docente.estudiante.cancelar');
            Route::get('/docente/representante/aprobar/{representante_estudiante}', 'Aplicacion\DocenteController@aprobarRepresentante')->name('docente.representante.aprobar');
            Route::resource('material-docente', 'Aplicacion\MaterialDocenteController');

            /**
             * Registrar estudiante
             */
            Route::resource('estudiante', 'Aplicacion\EstudianteController');

            /**
             * Representante
             */
            Route::resource('representante-estudiante', 'Aplicacion\RepresentanteEstudianteController');
            Route::post('representante-estudiante/asignar', 'Aplicacion\RepresentanteEstudianteController@asignarEstudianteRepresentante')->name('representante-estudiante.asignar');
            Route::get('representante-estudiante/cambiar/{user}', 'Aplicacion\RepresentanteEstudianteController@cambiarUsuarioEstudiante')->name('representante-estudiante.cambiar');

            /**
             * Calificar tareas
             */
            Route::resource('tarea', 'Aplicacion\TareaController');
            Route::get('tarea/calificar/{materialDocente}', 'Aplicacion\TareaController@calificar')->name('tarea.calificar');
            Route::get('tarea/calificar/{materialDocente}/{segmentoLibro}', 'Aplicacion\TareaController@calificar')
                ->name('tarea.calificar.segmento');
            Route::get('tarea/calificar/{materialDocente}/tarea/{tarea}', 'Aplicacion\TareaController@calificarTarea')
                ->name('tarea.calificar.tarea');

            Route::post('tarea/{materialEstudiante}/{desarrollo}', 'Aplicacion\TareaController@store')->name('tarea.calificar.store');

//            Route::get('detalle-registro-libro', 'Aplicacion\EstudianteController@detalleRegistroLibro')->name('estudiante.detalle-registro-libro');
//            Route::get('registrar-libro', 'Aplicacion\EstudianteController@registroLibro')->name('estudiante.registrar-libro');

//            Route::get('instituciones', 'Aplicacion\InstitucionController@index')->name('institucion.index');
//            Route::get('/institucion/create', 'Aplicacion\InstitucionController@create')->name('institucion.create');
//            Route::post('/institucion/store', 'Aplicacion\InstitucionController@store')->name('institucion.store');
//            Route::delete('/institucion/destroy/{estudiante}', 'Aplicacion\InstitucionController@destroy')->name('institucion.destroy');
        }
    );

// Adminitrator
Route::get('/admin', 'HomeController@index')
    ->name('admin.home');

Route::as('admin.')
    ->prefix('admin')
    ->group(
        function () {
            Route::resource('abreviatura', 'AbreviaturaController');
            Route::resource('asignatura', 'AsignaturaController');
            Route::resource('anio-lectivo', 'AnioLectivoController');
            Route::resource('institucion', 'InstitucionController');
            Route::resource('libro', 'LibroController');
            Route::resource('curso', 'CursoController');
            Route::resource('aula', 'AulaController');

            Route::resource('segmento_libro', 'SegmentoLibroController');
            Route::get('/segmento_libro/{libro}/index', 'SegmentoLibroController@index')->name('segmento_libro.index');
            Route::post('/segmento_libro/{libro}/store', 'SegmentoLibroController@store')->name('segmento_libro.store');

            Route::resource('tarea', 'TareaController');
            Route::get('/tarea/{segmentoLibro}/index', 'TareaController@index')->name('tarea.index');
            Route::post('/tarea/{segmentoLibro}/store', 'TareaController@store')->name('tarea.store');

            Route::resource('desarrollo', 'DesarrolloController');
            Route::get('/desarrollo/{tarea}/index', 'DesarrolloController@index')->name('desarrollo.index');
            Route::post('/desarrollo/{tarea}/store', 'DesarrolloController@store')->name('desarrollo.store');

            Route::resource('respuesta-desarrollo', 'RespuestaDesarrolloController');
            Route::post('/respuesta-desarrollo/{desarrollo}/store', 'RespuestaDesarrolloController@store')->name('respuesta-desarrollo.store');

            Route::resource('test', 'TestController');
            Route::get('/test/{segmentoLibro}/index', 'TestController@index')->name('test.index');
            Route::post('/test/{segmentoLibro}/store', 'TestController@store')->name('test.store');

            Route::resource('pregunta-desarrollo', 'PreguntaDesarrolloController');
            Route::get('/pregunta-desarrollo/{test}/index', 'PreguntaDesarrolloController@index')->name('pregunta-desarrollo.index');
            Route::post('/pregunta-desarrollo/{test}/store', 'PreguntaDesarrolloController@store')->name('pregunta-desarrollo.store');

            Route::resource('opcion-pregunta-desarrollo', 'OpcionPreguntaDesarrolloController');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/create', 'OpcionPreguntaDesarrolloController@create')->name('opcion-pregunta-desarrollo.create');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/index', 'OpcionPreguntaDesarrolloController@index')->name('opcion-pregunta-desarrollo.index');
            Route::post('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/store.imagen', 'OpcionPreguntaDesarrolloController@storeImagen')->name('opcion-pregunta-desarrollo.store.imagen');

app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;

class Libro extends Model
{
    use SoftDeletes;

    public static $paginate = 10;
    public static $search = null;
    protected $table = 'libro';
    protected $fillable = [
        'titulo',
        'resumen',
        'autor',
        'editorial',
        'edicion',
        'contenido',
        'indice_contenidos',
        'anio_lectivo_id',
        'asignatura_id',
        'curso_id',
        'portada',
        'anio_registro'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function curso()
    {
        return $this->belongsTo(Curso::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function asignatura()
    {
        return $this->belongsTo(Asignatura::class, 'asignatura_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function segmentoLibros()
    {
        return $this->hasMany(SegmentoLibro::class, 'libro_id', 'id');
    }

    public function getNombreLibroAttribute()
    {
        return "{$this->asignatura->nombre} / {$this->titulo} ({$this->curso->nombre})";
    }


    public function getAsignaturaNombreAttribute()
    {
        if($this->asignatura){
            return $this->asignatura->nombre;
        }

        return false;
    }

    /**
     * @return Builder
     */
    public static function builderLibro()
    {
        $query = Libro::orderBy('titulo', request('titulo', 'DESC'))
            ->orderBy('created_at', request('created_at', 'DESC'));

        if (self::$search) {
            $query->orWhere('titulo', 'like', '%' . self::$search . '%')
//                ->orWhere('anio', 'like', '%' . self::$search . '%')
//                ->orWhere('fecha_inicio', 'like', '%' . self::$search . '%')
//                ->orWhere('fecha_fin', 'like', '%' . self::$search . '%')
            ;
        }

        return $query;
    }

    /**
     * @return AnioLectivo[]|array
     */
    public static function obtenerLibroAll()
    {
        return self::builderLibro()->get() ?? [];
    }

    /**
     * @return AnioLectivo[]|array
     */
    public static function obtenerLibroCursoAll($curso_id)
    {
        $rs = self::builderLibro();
        $rs->where('curso_id', $curso_id);
        return $rs->get() ?? [];
    }

    /**
     * @param string|null $search
     * @return array|\Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public static function obtenerLibroPaginateAll()
    {
        return self::builderLibro()->paginate(self::$paginate) ?? [];
    }
}

app/Models/MaterialEstudiante.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;

class MaterialEstudiante extends Model
{

    public static $paginate = 10;
    public static $search = null;
    protected $table = 'material_estudiante';
    protected $fillable = [
        'material_docente_id',
        'estudiante_id',
        'estado_registro_id',
        'user_id',
        'codigo',
        'user_autoriza_id'
    ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function userAutoriza()
    {
        return $this->belongsTo(User::class, 'user_autoriza_id', 'id');
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function estudiante()
    {
        return $this->belongsTo(Estudiante::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function materialDocente()
    {
        return $this->belongsTo(MaterialDocente::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function estadoRegistro()
    {
        return $this->belongsTo(EstadoRegistro::class);
    }

    /**
     * @return mixed
     */
    public function getTituloLibroAttribute()
    {
        return $this->materialDocente->libro->titulo;
    }

    /**
     * @return mixed
     */
    public function getPortadaLibroAttribute()
    {
        return $this->materialDocente->libro->portada;
    }

    /**
     * @return mixed
     */
    public function getAsignaturaLibroAttribute()
    {
        return $this->materialDocente->libro->asignatura->nombre;
    }

    /**
     * @return mixed
     */
    public function getEstadoRegistroAnioLectivoAttribute()
    {
        return $this->estudiante->anioLectivo->estadoRegistro;
    }

    /**
     * @return mixed
     */
    public function getNombreEstudianteAttribute()
    {
        return $this->estudiante->nombre_estudiante;
    }


    /**
     * @return mixed
     */
    public function getCedulaEstudianteAttribute()
    {
        return $this->estudiante->cedula_estudiante;
    }


    /**
     * @return Builder
     */
    public static function builderMaterialEstudiante()
    {
        $query = MaterialEstudiante::orderBy('material_estudiante.created_at', request('created_at', 'DESC'));

        if (self::$search) {
            //$query->orWhere('descripcion', 'like', '%' . self::$search . '%');
        }

        return $query;
    }

    /**
     * @param User|integer $user
     * @return array
     */
    public static function obtenerMaterialEstudianteUser($user, $aprobados = false)
    {
        $rs = self::builderMaterialEstudiante();
        $rs->select('material_estudiante.*')
            ->join('estudiante', 'estudiante.id', '=', 'material_estudiante.estudiante_id')
            ->where('estudiante.user_id', (is_object($user)) ? $user->id : $user);

        if ($aprobados) {
            $rs->where('material_estudiante.estado_registro_id', ($estado = EstadoRegistro::obtenerEstadoRegistroAprobado()) ? $estado->id : null);
        }

        return $rs->get() ?? [];
    }

    /**
     * @param User|integer $user
     * @return array
     */
    public static function obtenerMaterialEstudianteMaterialDocenteEstudiante($materialDocente, $estudiante)
    {
        $aprobado = EstadoRegistro::obtenerEstadoRegistroAprobado();
        $revision = EstadoRegistro::obtenerEstadoRegistroRevision();

        $rs = self::builderMaterialEstudiante();
        $rs->where('material_docente_id', (is_object($materialDocente)) ? $materialDocente->id : $materialDocente)
            ->where('estudiante_id', (is_object($estudiante)) ? $estudiante->id : $estudiante)
            ->whereIn('estado_registro_id', [$aprobado->id, $revision->id]);

        return $rs->first() ?? [];
    }

    /**
     * @param User|integer $user
     * @return array
     */
    public static function obtenerMaterialEstudiantePaginate()
    {
        $rs = self::builderMaterialEstudiante();
        $rs->select('material_estudiante.*')
            ->join('estudiante', 'estudiante.id', '=', 'material_estudiante.estudiante_id')//            ->where('estudiante.user_id', $user->id)
        ;

        return $rs->paginate(self::$paginate) ?? [];
    }

    /**
     * @param User|integer $user
     * @return array
     */
    public static function obtenerMaterialEstudianteMaterialDocente($materialDocente)
    {
        $rs = self::builderMaterialEstudiante();
        $rs->select('material_estudiante.*')
            ->join('estudiante', 'estudiante.id', '=', 'material_estudiante.estudiante_id')
            ->where('material_docente_id', is_object($materialDocente) ? $materialDocente->id : $materialDocente);


        return $rs->get() ?? [];
    }
}

resources/views/aplicacion/material_estudiante/_form.blade.php
@csrf
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col col-8 text-aqua">
                <h6 class="m-0 font-weight-bold">Registro de libro</h6>
            </div>
        </div>
    </div>

    <div class="card-body">
        <div class="form-group">
            <label for="docente_id" class="bmd-label-floating">Instituci&oacute;n</label>
            <input type="hidden" name="id" id="id" value="{{old('id',$model->id)}}">
            <select class="form-control select2" id="estudiante_id" name="estudiante_id"
                    data-ajax--url="{{route('api.estudiante-user.select2',\App\Helpers\Sesiones::estudiante()->user->id)}}"
                    data-ajax--data-type="json"
                    data-allow-clear="true" data-placeholder="Seleccionar..." required>
                @if($model->estudiante_id)
                    <option value="{{$model->estudiante_id}}">
                        {{$model->estudiante->nombre_institucion}} - {{$model->estudiante->nombre_aula}}
                    </option>
                @endif
            </select>

            <div class="invalid-feedback">Por favor seleccione la instituci&oacute;n</div>
            <div class="valid-feedback"><i class="fe-check-circle"></i></div>

            @error('estudiante_id')
            <small class="text-danger">{{ $message }}</small>
            @enderror
        </div>

        <div class="form-group">
            <label for="libro_id" class="bmd-label-floating">Libro</label>
            <select class="form-control select2" name="material_docente_id" id="material_docente_id"
                    data-placeholder="Seleccionar..." required>
                @if($model->material_docente_id)
                    <option value="{{$model->material_docente_id}}">{{$model->materialDocente->libro->nombre_libro}}</option>
                @endif
            </select>

            <div class="invalid-feedback">Por favor seleccione el libro</div>
            <div class="valid-feedback"><i class="fe-check-circle"></i></div>

            @error('material_docente_id')
            <small class="text-danger">{{ $message }}</small>
            @enderror
        </div>

        <div class="form-group">
            <label for="libro_id" class="bmd-label-floating">C&oacute;digo de registro</label>
            <input class="form-control" type="text" id="codigo" name="codigo" data-format="custom" data-delimiter="-"
                   data-blocks="3 4 5" placeholder="000-0000-00000" value="{{old('codigo',$model->codigo)}}">
        </div>

        <input type="hidden" id="token" value="{{ csrf_token() }}">

        <input type="submit" value="Enviar" class="btn btn-primary">

    </div>
</div>

resources/views/aplicacion/material_estudiante/create.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    {{ Breadcrumbs::render('app.registro-libro.create', $model ?? '') }}
@endsection

@section('content')
    @include('includes.validation-error-admin')
    <form action="{{ route("app.material-estudiante.store") }}" method="POST" enctype='multipart/form-data'
          class="needs-validation" novalidate>
        @include('aplicacion.material_estudiante._form')
    </form>
@endsection

@section('scripts')
    <script src="{{asset('js/formSubmit.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var select2Options = {width: 'resolve'};
            var apiUrl = "{{route('api.material-docente.select2',0)}}";
            window.Select2Cascade($('#estudiante_id'), $('#material_docente_id'), apiUrl, select2Options);

            $('#material_docente_id').on('select2:select', function () {
                window.cargarCampoRegistroLibro($('#material_docente_id').val(), "{{route('api.material-docente.codigo')}}", 'codigo');
            });
        });
    </script>
@endsection

resources/views/aplicacion/material_estudiante/edit.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    {{ Breadcrumbs::render('admin.libro.create', $model ?? '') }}
@endsection

@section('content')
    @include('includes.validation-error-admin')
    <form action="{{ route("app.material-estudiante.update",$model->id) }}" method="POST" enctype='multipart/form-data'
          novalidate>
        @method('PUT')
        @include('aplicacion.material_estudiante._form')
    </form>
@endsection


@section('scripts')
    <script src="{{asset('js/formSubmit.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var select2Options = {width: 'resolve'};
            var apiUrl = "{{route('api.libro-estudiante.select2',0)}}";
            window.Select2Cascade($('#estudiante_id'), $('#libro_id'), apiUrl, select2Options);


            window.cargarCampoRegistroLibro($('#material_docente_id').val(), "{{route('api.material-docente.codigo')}}", 'codigo');

            $('#material_docente_id').on('select2:select', function () {
                window.cargarCampoRegistroLibro($('#material_docente_id').val(), "{{route('api.material-docente.codigo')}}", 'codigo');
            });
        });
    </script>
@endsection

resources/views/aplicacion/material_estudiante/index.blade.php
@extends('layouts.aplicacion.app')
@php
    use App\Helpers\CodigoRegistroLibro;
    use App\Helpers\Helper;
@endphp

@section('breadcrum')
    {{ Breadcrumbs::render('app.registro-libro.index', $model ?? '') }}
@endsection

@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <div class="row">
                <div class="col col-9">
                    <h4 class="card-title">
                        Mis Libros
                    </h4>
                    <div class="card-category">
                        Registro de libros ingresados para desarrollar
                    </div>
                </div>
                <div class="col col-3 text-right">
                    <a class="btn btn-success btn-sm" href="{{ route('app.material-estudiante.create') }}">
                        <i class="fe-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th>&nbsp;</th>
                    <th>Asignatura</th>
                    <th>Libro</th>
                    <th>C&oacute;digo</th>
                    <th>Registro</th>
                    <th>Estado</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($materialesEstudiante as $materialEstudiante)
                    @php
                        CodigoRegistroLibro::validarRegistroLibro($materialEstudiante->materialDocente->libro, $materialEstudiante->codigo);
                    @endphp

                    <tr>
                        <td>
                            <img class="img-thumbnail" width="100"
                                 src="{{asset('/storage/portada_libro/'.$materialEstudiante->portada_libro)}}"
                                 alt="{{$materialEstudiante->titulo_libro}}"/>
                        </td>
                        <td class="py-3 align-middle">
                            <div class="media-body">
                                <span class="font-weight-medium text-heading mr-1">
                                    {{$materialEstudiante->asignatura_libro}}
                                </span>
                            </div>
                        </td>
                        <td class="py-3 align-middle">
                            <div class="media align-items-center">
                                <div class="media-body">
                                    {{$materialEstudiante->titulo_libro}}
                                    {!! Helper::obtenerEstadoEnCursoInactivo($materialEstudiante->estado_registro_anio_lectivo->codigo) !!}
                                </div>
                            </div>
                        </td>
                        <td class="py-3 align-middle">
                            {{$materialEstudiante->codigo}}
                            {!! CodigoRegistroLibro::$mensajePrincipal !!}
                        </td>
                        <td class="py-3 align-middle">
                            <small>{{ $materialEstudiante->created_at->format('M d Y h:i') }}</small>
                        </td>
                        <td class="py-3 align-middle">
                            {!! Helper::obtenerIconEstado($materialEstudiante->estadoRegistro->codigo) !!}
                            <small>{{$materialEstudiante->estadoRegistro->nombre}}</small>
                        </td>
                        <td class="py-3 align-middle text-center">
                            <a href="{{route('app.material-estudiante.edit',$materialEstudiante->id)}}"
                               data-toggle="tooltip" title="{{__('EDITAR')}}"
                               class="nav-link-style mr-1">
                                <i class="fe-edit"></i>
                            </a>
                            <a data-toggle="modal" data-target="#deleteModal" data-id="{{ $materialEstudiante->id }}"
                               class="nav-link-style mr-1 text-danger">
                                <i class="fe-trash-2"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    @include('includes.forms.modal-delete',['name_route'=>'app.material-estudiante.destroy'])

@endsection

@section('scripts')
    <script type="text/javascript">
        window.deleteModalAjax('deleteModal');
    </script>
@endsection