routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Corporativas
Route::get('/', 'Corporativa\FrontendController@home')->name('corporativa.home');

Route::get('/test', function () {
    return view('corporativa/home');
})->name('corporativa.test');

Route::as('corporativa.')
    ->prefix('libertad')
    ->group(
        function () {
            Route::get('acerca-de', 'Corporativa\FrontendController@acerca_de')->name('acerca_de');
            Route::get('contacto', 'Corporativa\FrontendController@contacto')->name('contacto');
            Route::get('libreria', 'Corporativa\FrontendController@libreria')->name('libreria');
            Route::get('instituciones', 'Corporativa\FrontendController@instituciones')->name('instituciones');
        }
    );

// Aplicacion
Route::as('app.')
    ->prefix('app')
    ->group(
        function () {
            Route::get('/', 'Aplicacion\FrontendController@dashboard')->name('dashboard');
            Route::get('mis-suscripciones', 'Aplicacion\FrontendController@mis_suscripciones')->name('representante-suscripciones');
            Route::get('listado-de-tareas', 'Aplicacion\FrontendController@listado_tareas')->name('representante-tareas');
            Route::get('listado-de-tests', 'Aplicacion\FrontendController@listado_tests')->name('representante-tests');

            /**
             * Rutas para desarrollar los libros por el usuario
             */
            Route::get('libros', 'Aplicacion\FrontendController@listado_libros')->name('libros');
            Route::get('/archivo/{segmentoLibro}/revista', 'Aplicacion\LibroController@revista_archivo')->name('archivo.revista');
            Route::get('/archivo/{segmentoLibro}/download', 'Aplicacion\LibroController@downloadSegmentoLibro')->name('archivo.download');
//            Route::get('/tarea/{tarea}/desarrollo', 'Aplicacion\LibroController@desarrolloTarea')->name('tarea.desarrollo');
            Route::get('/test/{test}/desarrollo', 'Aplicacion\LibroController@desarrolloTest')->name('test.desarrollo');

            /**
             * Desarrollo de Tareas
             */
            Route::get('/desarrollo/{material_estudiante}', 'Aplicacion\DesarrolloController@index')
                ->name('desarrollo.index')
                ->middleware('auth');
            Route::get('/desarrollo/{material_estudiante}/{tarea}', 'Aplicacion\DesarrolloController@tarea')
                ->name('desarrollo.tarea')
                ->middleware('auth');
            Route::post('/desarrollo/{materialEstudiante}', 'Aplicacion\DesarrolloController@store')
                ->name('desarrollo.store')
                ->middleware('auth');

            /**
             * Rutas para administrar el perfil del usuario
             */
            Route::get('/user/perfil', 'Aplicacion\UserController@perfil')->name('user.perfil');
            Route::post('/user/perfil/{user}/store', 'Aplicacion\UserController@storePerfil')->name('user.perfil.store');
            Route::post('/user/perfil/{user}/store_rol_user', 'Aplicacion\UserController@storeRolUser')->name('user.rol_user.store');
            Route::delete('/user/perfil/destroy_rol_user/{rolesUsers}', 'Aplicacion\UserController@destroyRol')->name('user.rol_user.destroy');

            /**
             * Rutas para registrar los libros por el usuario
             */
            Route::resource('material-estudiante', 'Aplicacion\MaterialEstudianteController');

            /**
             * Registrar docente
             */
            Route::resource('docente', 'Aplicacion\DocenteController');
            Route::get('/docente/estudiante/detalle', 'Aplicacion\DocenteController@detalleEstudiantesAprobar')->name('docente.estudiante.index');
            Route::get('/docente/estudiante/aprobar/{estudiante}', 'Aplicacion\DocenteController@aprobarEstudiante')->name('docente.estudiante.aprobar');
            Route::get('/docente/estudiante/cancelar/{estudiante}', 'Aplicacion\DocenteController@cancelarEstudiante')->name('docente.estudiante.cancelar');
            Route::get('/docente/representante/aprobar/{representante_estudiante}', 'Aplicacion\DocenteController@aprobarRepresentante')->name('docente.representante.aprobar');
            Route::resource('material-docente', 'Aplicacion\MaterialDocenteController');

            /**
             * Registrar estudiante
             */
            Route::resource('estudiante', 'Aplicacion\EstudianteController');

            /**
             * Representante
             */
            Route::resource('representante-estudiante', 'Aplicacion\RepresentanteEstudianteController');
            Route::post('representante-estudiante/asignar', 'Aplicacion\RepresentanteEstudianteController@asignarEstudianteRepresentante')->name('representante-estudiante.asignar');
            Route::get('representante-estudiante/cambiar/{user}', 'Aplicacion\RepresentanteEstudianteController@cambiarUsuarioEstudiante')->name('representante-estudiante.cambiar');

            /**
             * Calificar tareas
             */
            Route::resource('tarea', 'Aplicacion\TareaController');
            Route::get('tarea/calificar/{materialDocente}', 'Aplicacion\TareaController@calificar')->name('tarea.calificar');
            Route::get('tarea/calificar/{materialDocente}/{segmentoLibro}', 'Aplicacion\TareaController@calificar')
                ->name('tarea.calificar.segmento');
            Route::get('tarea/calificar/{materialDocente}/tarea/{tarea}', 'Aplicacion\TareaController@calificarTarea')
                ->name('tarea.calificar.tarea');

            Route::post('tarea/{materialEstudiante}/{desarrollo}', 'Aplicacion\TareaController@store')->name('tarea.calificar.store');

//            Route::get('detalle-registro-libro', 'Aplicacion\EstudianteController@detalleRegistroLibro')->name('estudiante.detalle-registro-libro');
//            Route::get('registrar-libro', 'Aplicacion\EstudianteController@registroLibro')->name('estudiante.registrar-libro');

//            Route::get('instituciones', 'Aplicacion\InstitucionController@index')->name('institucion.index');
//            Route::get('/institucion/create', 'Aplicacion\InstitucionController@create')->name('institucion.create');
//            Route::post('/institucion/store', 'Aplicacion\InstitucionController@store')->name('institucion.store');
//            Route::delete('/institucion/destroy/{estudiante}', 'Aplicacion\InstitucionController@destroy')->name('institucion.destroy');
        }
    );

// Adminitrator
Route::get('/admin', 'HomeController@index')
    ->name('admin.home');

Route::as('admin.')
    ->prefix('admin')
    ->group(
        function () {
            Route::resource('abreviatura', 'AbreviaturaController');
            Route::resource('asignatura', 'AsignaturaController');
            Route::resource('anio-lectivo', 'AnioLectivoController');
            Route::resource('institucion', 'InstitucionController');
            Route::resource('libro', 'LibroController');
            Route::resource('curso', 'CursoController');
            Route::resource('aula', 'AulaController');

            Route::resource('segmento_libro', 'SegmentoLibroController');
            Route::get('/segmento_libro/{libro}/index', 'SegmentoLibroController@index')->name('segmento_libro.index');
            Route::post('/segmento_libro/{libro}/store', 'SegmentoLibroController@store')->name('segmento_libro.store');

            Route::resource('tarea', 'TareaController');
            Route::get('/tarea/{segmentoLibro}/index', 'TareaController@index')->name('tarea.index');
            Route::post('/tarea/{segmentoLibro}/store', 'TareaController@store')->name('tarea.store');

            Route::resource('desarrollo', 'DesarrolloController');
            Route::get('/desarrollo/{tarea}/index', 'DesarrolloController@index')->name('desarrollo.index');
            Route::post('/desarrollo/{tarea}/store', 'DesarrolloController@store')->name('desarrollo.store');

            Route::resource('respuesta-desarrollo', 'RespuestaDesarrolloController');
            Route::post('/respuesta-desarrollo/{desarrollo}/store', 'RespuestaDesarrolloController@store')->name('respuesta-desarrollo.store');

            Route::resource('test', 'TestController');
            Route::get('/test/{segmentoLibro}/index', 'TestController@index')->name('test.index');
            Route::post('/test/{segmentoLibro}/store', 'TestController@store')->name('test.store');

            Route::resource('pregunta-desarrollo', 'PreguntaDesarrolloController');
            Route::get('/pregunta-desarrollo/{test}/index', 'PreguntaDesarrolloController@index')->name('pregunta-desarrollo.index');
            Route::post('/pregunta-desarrollo/{test}/store', 'PreguntaDesarrolloController@store')->name('pregunta-desarrollo.store');

            Route::resource('opcion-pregunta-desarrollo', 'OpcionPreguntaDesarrolloController');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/create', 'OpcionPreguntaDesarrolloController@create')->name('opcion-pregunta-desarrollo.create');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/index', 'OpcionPreguntaDesarrolloController@index')->name('opcion-pregunta-desarrollo.index');
            Route::post('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/store.imagen', 'OpcionPreguntaDesarrolloController@storeImagen')->name('opcion-pregunta-desarrollo.store.imagen');

app/Http/Controllers/Aplicacion/DesarrolloController.php
<?php

namespace App\Http\Controllers\Aplicacion;

use App\Helpers\Archivos;
use App\Http\Controllers\Controller;
use App\Http\Requests\Desarrollo\StorePostEstudiante;
use App\Models\DesarrolloEstudiante;
use App\Models\MaterialEstudiante;
use App\Models\RespuestaDesarrollo;
use App\Models\SegmentoLibro;
use App\Models\Tarea;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class DesarrolloController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(MaterialEstudiante $materialEstudiante)
    {
        $libro = $materialEstudiante->materialDocente->libro;
        $segmentoLibros = SegmentoLibro::obtenerSegmentoLibroAll($libro->id);
        return view('aplicacion.libro.index', compact('libro', 'segmentoLibros', 'materialEstudiante'));
    }

    /**
     * @param MaterialEstudiante $materialEstudiante
     * @param Tarea $tarea
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function tarea(MaterialEstudiante $materialEstudiante, Tarea $tarea)
    {
        return view('aplicacion.libro._desarrollo', compact('tarea', 'materialEstudiante'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostEstudiante $request, MaterialEstudiante $materialEstudiante)
    {
        DB::beginTransaction();

        $requestData = $request->validated();
        $validator = Validator::make($requestData, StorePostEstudiante::myRules());

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            $errors = [];
            if ($request->has('file')) {
                foreach ($request->file('file') as $respuesta_desarrollo_id => $file) {
                    if ($file) {
                        if ($respuestaDesarrollo = RespuestaDesarrollo::find($respuesta_desarrollo_id)) {
                            if ($archivo = Archivos::storeArchivoDesarrolloEstudiante($materialEstudiante, $file)) {
                                if (!($desarrolloEstudiante = DesarrolloEstudiante::getDesarrolloEstudianteMaterialEstudianteRespuestaDesarrollo($materialEstudiante, $respuestaDesarrollo))) {
                                    $desarrolloEstudiante = new DesarrolloEstudiante();
                                }

                                $desarrolloEstudiante->archivo = $archivo;
                                $desarrolloEstudiante->tipo_calificacion_id = $respuestaDesarrollo->desarrollo->tarea->tipo_calificacion_id ?? null;
                                $desarrolloEstudiante->material_estudiante_id = $materialEstudiante->id ?? null;
                                $desarrolloEstudiante->respuesta_desarrollo_id = $respuestaDesarrollo->id;

                                $desarrolloEstudiante->save();
                                //DesarrolloEstudiante::create($requestData);
                            }
                        }
                    } else {
                        $errors['file_' . $respuesta_desarrollo_id] = ['Por favor seleccione un archivo'];
                    }
                }
            } else {
                $errors['file'] = ['Por favor ingrese el contenido necesario'];
            }

            if ($request->has('respuesta')) {
                foreach ($request->get('respuesta') as $respuesta_desarrollo_id => $respuesta) {
                    if ($respuesta) {
                        if ($respuestaDesarrollo = RespuestaDesarrollo::find($respuesta_desarrollo_id)) {
                            if (!($desarrolloEstudiante = DesarrolloEstudiante::getDesarrolloEstudianteMaterialEstudianteRespuestaDesarrollo($materialEstudiante, $respuestaDesarrollo))) {
                                $desarrolloEstudiante = new DesarrolloEstudiante();
                            }

                            $desarrolloEstudiante->respuesta = $respuesta;
                            $desarrolloEstudiante->tipo_calificacion_id = $respuestaDesarrollo->desarrollo->tarea->tipo_calificacion_id ?? null;
                            $desarrolloEstudiante->material_estudiante_id = $materialEstudiante->id ?? null;
                            $desarrolloEstudiante->respuesta_desarrollo_id = $respuestaDesarrollo->id;

                            $desarrolloEstudiante->save();
                            // DesarrolloEstudiante::create($requestData);
                        }
                    } else {
                        $errors['respuesta_' . $respuesta_desarrollo_id] = ['Por favor ingrese el contenido necesario'];
                    }
                }
            }

            if (!$errors) {
                DB::commit();
                return response()->json([
                    'status' => 'success',
                    'message' => 'Tarea registrada exitosamente'
                ]);
            } else {
                return response()->json([
                    'errors' => $errors
                ], 400);
            }
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        } catch (\Throwable $e) {
            DB::rollback();
            throw $e;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\MaterialEstudiante $materialEstudiante
     * @return \Illuminate\Http\Response
     */
    public function show(MaterialEstudiante $materialEstudiante)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\MaterialEstudiante $materialEstudiante
     * @return \Illuminate\Http\Response
     */
    public function edit(MaterialEstudiante $materialEstudiante)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\MaterialEstudiante $materialEstudiante
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MaterialEstudiante $materialEstudiante)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\MaterialEstudiante $materialEstudiante
     * @return \Illuminate\Http\Response
     */
    public function destroy(MaterialEstudiante $materialEstudiante)
    {
        //
    }

}

resources/views/backend/desarrollo/_detalle_respuestas.blade.php
@php
    $respuestas = \App\Models\RespuestaDesarrollo::obtenerRespuestaDesarrolloDesarrolloAll($desarrollo->id);
@endphp


<dl class="row pb-0 mb-0">
    @foreach($respuestas as $respuesta)
        <dd class="col-sm-10 small text-uppercase">
            <i class="fe-check-circle text-success"></i> {{$respuesta->tipoRespuesta->descripcion}}
        </dd>
        <dd class="col-sm-2 text-center">
            <a data-toggle="modal" data-target="#deleteModal-respuesta"
               data-id="{{ $respuesta->id }}" class="nav-link-style">
                <i class="fe-trash-2 text-danger"></i>
            </a>
        </dd>
    @endforeach
</dl>

resources/views/backend/desarrollo/_form.blade.php
@csrf
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col col-8 text-aqua">
                <h6 class="m-0 font-weight-bold">
                    Desarrollo: {{$tarea->segmentoLibro->libro->titulo}} - {{$tarea->segmentoLibro->unidad}}
                </h6>
            </div>
        </div>

    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="row">
                <div class="col col-12 mt-2">
                    <blockquote class="blockquote">
                        <p class="mb-0 text-primary">Tarea</p>
                        <footer class="blockquote-footer text-justify">{!! $tarea->objetivo !!}</footer>
                    </blockquote>
                </div>
                <div class="col col-md-8 mt-2">
                    <label for="unidad" class="bmd-label-floating">Desarrollo</label>
                    <textarea name="descripcion" id="descripcion" class="form-control ckeditor-content">
                        {{$model->descripcion}}
                    </textarea>

                    @error('descripcion')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col col-md-4 mt-2">
                    <label for="imagen" class="bmd-label-floating">Imagen</label>
                    <input type="file" class="dropify" name="imagen" id="imagen"
                           @if($model->imagen) data-default-file="{{url('storage/desarrollo/imagen/'.$model->imagen)}}" @endif>

                    @error('imagen')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <input type="hidden" id="token" value="{{ csrf_token() }}">
            <input type="submit" value="Cargar" class="mt-3 btn btn-primary" id="cargar-libro">
        </div>
    </div>
</div>

resources/views/backend/desarrollo/create.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    <div class="row ">
        {{--<div class="col col-7">--}}
        <div class="col col-5">
            @if(!$model->id)
                <div class="alert alert-primary" role="alert">
                    Crear nuevo desarrollo
                </div>
            @else
                <div class="alert alert-warning" role="alert">
                    Actualizar desarrollo #{{$model->id}}
                </div>
            @endif
        </div>
        <div class="col col-6">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.home')}}">Inicio</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.libro.index')}}">Libros</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.segmento_libro.index',$tarea->segmentoLibro->libro_id)}}">
                            Unidades
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.tarea.index',$tarea->segmentoLibro->id)}}">
                            Tareas
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Desarrollo
                    </li>
                </ol>
            </nav>
        </div>
        <div class="col col-1 text-center">
            <a class="btn btn-success btn-sm mt-2"
               href="{{ route('admin.desarrollo.index',$tarea->id) }}">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
@endsection

@section('content')
    @include('includes.validation-error-admin')
    <div class="row">
        <div class="col col-12">
            <form id="form-archivo"
                  @if(!$model->id)
                  action="{{ route("admin.desarrollo.store",$tarea->id) }}"
                  @else
                  action="{{ route("admin.desarrollo.update",$model->id) }}"
                  @endif
                  method="POST"
                  enctype='multipart/form-data'>
                @if(!$model->id)
                    @method('POST')
                @else
                    @method('PUT')
                @endif

                @include('backend.desarrollo._form', compact('tarea','model'))
            </form>
        </div>
        <div class="col col-12">
            @include('backend.desarrollo.index', compact('desarrollos'))
        </div>
    </div>
    @include('includes.forms.modal-delete',['name_route'=>'admin.desarrollo.destroy'])
    @include('includes.forms.modal-delete',[
     'idmodal'=>'deleteModal-respuesta',
     'formDelete'=>'formdelete-respuesta',
     'name_route'=>'admin.respuesta-desarrollo.destroy',
     'button'=>'button',
     'id_button'=>"eliminar-respuesta"
    ])
@endsection

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            // $.ajaxSetup({
            //     headers: {
            //         'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            //     },
            // });

            $(document).on('click', '.guardar-respuesta', function () {
                var id = $(this).data('id');
                respuestaDesarrollo(id);
            });

            $(document).on('click', '#eliminar-respuesta', function () {
                var url = $('#formdelete-respuesta').attr('action');
                eliminarRespuesta(url);
            });

            window.deleteModalAjax('deleteModal');

            window.deleteModalAjax('deleteModal-respuesta');

        });

        // (function () {
        //     window.onload = function () {
        //         $.ajaxSetup({
        //             headers: {
        //                 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        //             },
        //         });

        // $('#deleteModal').on('show.bs.modal', function (event) {
        //     var button = $(event.relatedTarget); // Button that triggered the modal
        //     var id = button.data('id'); // Extract info from data-* attributes
        //     // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        //     // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        //
        //     action = $('#formDelete').attr('data-action').slice(0, -1);
        //     action += id;
        //     console.log(action);
        //
        //     $('#formDelete').attr('action', action);
        //
        //     var modal = $(this);
        //     modal.find('.modal-title').text('Borrar Tarea #' + id);
        // });
        //
        // $('#deleteModal-respuesta').on('show.bs.modal', function (event) {
        //     var button = $(event.relatedTarget); // Button that triggered the modal
        //     var id = button.data('id'); // Extract info from data-* attributes
        //     // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        //     // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        //
        //     action = $('#formdelete-respuesta').attr('data-action').slice(0, -1);
        //     action += id;
        //
        //     $('#formdelete-respuesta').attr('action', action);
        //
        //     var modal = $(this);
        //     modal.find('.modal-title').text('Borrar Respuesta del desarrollo #' + id);
        // });
        //     };
        // })();

        function respuestaDesarrollo(desarrollo_id) {
            var form = $('#form-respuesta-desarrollo-' + desarrollo_id);
            var url = form.attr('action');
            $.ajax({
                type: "POST",
                url: url,
                data: form.serialize(),
                dataType: 'Json',
                success: function (data) {
                    window.showCustomSucces(data.success);
                    detallerRespuesta(desarrollo_id)
                },
                error: function (data) {
                    window.showCustomError(data.responseText);
                }
            });
        }

        function eliminarRespuesta(url) {
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                type: "DELETE",
                url: url,
                success: function (data) {
                    window.showCustomSucces(data.success);
                    detallerRespuesta(data.desarrollo_id);
                },
                error: function (data) {
                    window.showCustomError(data.responseText);
                }
            });
        }

        function detallerRespuesta(id) {
            $.ajax({
                type: "GET",
                url: "{{route('admin.respuesta-desarrollo.index')}}",
                data: {id: id},
                success: function (data) {
                    $('#detalle-respuesta-desarrollo-' + id).html(data.html);
                },
                error: function (data) {
                    window.showCustomError(data.responseText);
                }
            });
        }
    </script>
@endsection

resources/views/backend/desarrollo/index.blade.php
<div class="card">
    <div class="card-header card-header-primary">
        <div class="row">
            <div class="col col-9">
                <h6 class="strong">Respuesta para el desarrollo </h6>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Desarrollo</th>
                <th>Imagen</th>
                <th>Respuesta</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            @foreach($desarrollos as $desarrollo)
                <tr>
                    <td class="w-50 text-justify">{!! $desarrollo->descripcion !!}</td>
                    <td>
                        <div style="width: 250px;">
                            <img src="{{url('storage/desarrollo/imagen/'.$model->imagen)}}" alt="{{$model->imagen}}">
                        </div>
                    </td>
                    <td>
                        <div style="width: 250px;">
                            <form id="form-respuesta-desarrollo-{{$desarrollo->id}}"
                                  action="{{route('admin.respuesta-desarrollo.store',$desarrollo->id)}}">
                                @csrf
                                <div id="detalle-respuesta-desarrollo-{{$desarrollo->id}}">
                                    @include('backend.desarrollo._detalle_respuestas',compact('desarrollo'))
                                </div>

                                <select name="tipo_respuesta_id" id="tipo_respuesta_id_{{$desarrollo->id}}"
                                        class="w-100 form-control select2"
                                        data-ajax--url="{{ route('api.tipo_respuesta.select2') }}">

                                </select>
                                <div class="mt-1 text-right">
                                    <button data-id="{{$desarrollo->id}}" type="button"
                                            class="guardar-respuesta btn btn-outline-primary btn-sm">
                                        Ingresar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="text-center" style="width: 80px">
                            <a href="{{route('admin.desarrollo.edit',$desarrollo->id)}}" class="nav-link-style mr-1"
                               data-toggle="tooltip" data-placement="top"
                               title="{{__('EDITAR')}}">
                                <i class="fe-edit-2"></i>
                            </a>
                            <a data-toggle="modal" data-target="#deleteModal" data-id="{{ $desarrollo->id }}"
                               class="nav-link-style text-danger">
                                <i class="fe-trash-2"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="m-3">
            {{--{{--}}
            {{--$libros--}}
            {{--->appends(['created_at' => request('created_at'),'search' => request('search'),])--}}
            {{--->links()--}}
            {{--}}--}}
        </div>
    </div>
</div>