routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Corporativas
Route::get('/', 'Corporativa\FrontendController@home')->name('corporativa.home');

Route::get('/test', function () {
    return view('corporativa/home');
})->name('corporativa.test');

Route::as('corporativa.')
    ->prefix('libertad')
    ->group(
        function () {
            Route::get('acerca-de', 'Corporativa\FrontendController@acerca_de')->name('acerca_de');
            Route::get('contacto', 'Corporativa\FrontendController@contacto')->name('contacto');
            Route::get('libreria', 'Corporativa\FrontendController@libreria')->name('libreria');
            Route::get('instituciones', 'Corporativa\FrontendController@instituciones')->name('instituciones');
        }
    );

// Aplicacion
Route::as('app.')
    ->prefix('app')
    ->group(
        function () {
            Route::get('/', 'Aplicacion\FrontendController@dashboard')->name('dashboard');
            Route::get('mis-suscripciones', 'Aplicacion\FrontendController@mis_suscripciones')->name('representante-suscripciones');
            Route::get('listado-de-tareas', 'Aplicacion\FrontendController@listado_tareas')->name('representante-tareas');
            Route::get('listado-de-tests', 'Aplicacion\FrontendController@listado_tests')->name('representante-tests');

            /**
             * Rutas para desarrollar los libros por el usuario
             */
            Route::get('libros', 'Aplicacion\FrontendController@listado_libros')->name('libros');
            Route::get('/archivo/{segmentoLibro}/revista', 'Aplicacion\LibroController@revista_archivo')->name('archivo.revista');
            Route::get('/archivo/{segmentoLibro}/download', 'Aplicacion\LibroController@downloadSegmentoLibro')->name('archivo.download');
//            Route::get('/tarea/{tarea}/desarrollo', 'Aplicacion\LibroController@desarrolloTarea')->name('tarea.desarrollo');
            Route::get('/test/{test}/desarrollo', 'Aplicacion\LibroController@desarrolloTest')->name('test.desarrollo');

            /**
             * Desarrollo de Tareas
             */
            Route::get('/desarrollo/{material_estudiante}', 'Aplicacion\DesarrolloController@index')
                ->name('desarrollo.index')
                ->middleware('auth');
            Route::get('/desarrollo/{material_estudiante}/{tarea}', 'Aplicacion\DesarrolloController@tarea')
                ->name('desarrollo.tarea')
                ->middleware('auth');
            Route::post('/desarrollo/{materialEstudiante}', 'Aplicacion\DesarrolloController@store')
                ->name('desarrollo.store')
                ->middleware('auth');

            /**
             * Rutas para administrar el perfil del usuario
             */
            Route::get('/user/perfil', 'Aplicacion\UserController@perfil')->name('user.perfil');
            Route::post('/user/perfil/{user}/store', 'Aplicacion\UserController@storePerfil')->name('user.perfil.store');
            Route::post('/user/perfil/{user}/store_rol_user', 'Aplicacion\UserController@storeRolUser')->name('user.rol_user.store');
            Route::delete('/user/perfil/destroy_rol_user/{rolesUsers}', 'Aplicacion\UserController@destroyRol')->name('user.rol_user.destroy');

            /**
             * Rutas para registrar los libros por el usuario
             */
            Route::resource('material-estudiante', 'Aplicacion\MaterialEstudianteController');

            /**
             * Registrar docente
             */
            Route::resource('docente', 'Aplicacion\DocenteController');
            Route::get('/docente/estudiante/detalle', 'Aplicacion\DocenteController@detalleEstudiantesAprobar')->name('docente.estudiante.index');
            Route::get('/docente/estudiante/aprobar/{estudiante}', 'Aplicacion\DocenteController@aprobarEstudiante')->name('docente.estudiante.aprobar');
            Route::get('/docente/estudiante/cancelar/{estudiante}', 'Aplicacion\DocenteController@cancelarEstudiante')->name('docente.estudiante.cancelar');
            Route::get('/docente/representante/aprobar/{representante_estudiante}', 'Aplicacion\DocenteController@aprobarRepresentante')->name('docente.representante.aprobar');
            Route::resource('material-docente', 'Aplicacion\MaterialDocenteController');

            /**
             * Registrar estudiante
             */
            Route::resource('estudiante', 'Aplicacion\EstudianteController');

            /**
             * Representante
             */
            Route::resource('representante-estudiante', 'Aplicacion\RepresentanteEstudianteController');
            Route::post('representante-estudiante/asignar', 'Aplicacion\RepresentanteEstudianteController@asignarEstudianteRepresentante')->name('representante-estudiante.asignar');
            Route::get('representante-estudiante/cambiar/{user}', 'Aplicacion\RepresentanteEstudianteController@cambiarUsuarioEstudiante')->name('representante-estudiante.cambiar');

            /**
             * Calificar tareas
             */
            Route::resource('tarea', 'Aplicacion\TareaController');
            Route::get('tarea/calificar/{materialDocente}', 'Aplicacion\TareaController@calificar')->name('tarea.calificar');
            Route::get('tarea/calificar/{materialDocente}/{segmentoLibro}', 'Aplicacion\TareaController@calificar')
                ->name('tarea.calificar.segmento');
            Route::get('tarea/calificar/{materialDocente}/tarea/{tarea}', 'Aplicacion\TareaController@calificarTarea')
                ->name('tarea.calificar.tarea');

            Route::post('tarea/{materialEstudiante}/{desarrollo}', 'Aplicacion\TareaController@store')->name('tarea.calificar.store');

//            Route::get('detalle-registro-libro', 'Aplicacion\EstudianteController@detalleRegistroLibro')->name('estudiante.detalle-registro-libro');
//            Route::get('registrar-libro', 'Aplicacion\EstudianteController@registroLibro')->name('estudiante.registrar-libro');

//            Route::get('instituciones', 'Aplicacion\InstitucionController@index')->name('institucion.index');
//            Route::get('/institucion/create', 'Aplicacion\InstitucionController@create')->name('institucion.create');
//            Route::post('/institucion/store', 'Aplicacion\InstitucionController@store')->name('institucion.store');
//            Route::delete('/institucion/destroy/{estudiante}', 'Aplicacion\InstitucionController@destroy')->name('institucion.destroy');
        }
    );

// Adminitrator
Route::get('/admin', 'HomeController@index')
    ->name('admin.home');

Route::as('admin.')
    ->prefix('admin')
    ->group(
        function () {
            Route::resource('abreviatura', 'AbreviaturaController');
            Route::resource('asignatura', 'AsignaturaController');
            Route::resource('anio-lectivo', 'AnioLectivoController');
            Route::resource('institucion', 'InstitucionController');
            Route::resource('libro', 'LibroController');
            Route::resource('curso', 'CursoController');
            Route::resource('aula', 'AulaController');

            Route::resource('segmento_libro', 'SegmentoLibroController');
            Route::get('/segmento_libro/{libro}/index', 'SegmentoLibroController@index')->name('segmento_libro.index');
            Route::post('/segmento_libro/{libro}/store', 'SegmentoLibroController@store')->name('segmento_libro.store');

            Route::resource('tarea', 'TareaController');
            Route::get('/tarea/{segmentoLibro}/index', 'TareaController@index')->name('tarea.index');
            Route::post('/tarea/{segmentoLibro}/store', 'TareaController@store')->name('tarea.store');

            Route::resource('desarrollo', 'DesarrolloController');
            Route::get('/desarrollo/{tarea}/index', 'DesarrolloController@index')->name('desarrollo.index');
            Route::post('/desarrollo/{tarea}/store', 'DesarrolloController@store')->name('desarrollo.store');

            Route::resource('respuesta-desarrollo', 'RespuestaDesarrolloController');
            Route::post('/respuesta-desarrollo/{desarrollo}/store', 'RespuestaDesarrolloController@store')->name('respuesta-desarrollo.store');

            Route::resource('test', 'TestController');
            Route::get('/test/{segmentoLibro}/index', 'TestController@index')->name('test.index');
            Route::post('/test/{segmentoLibro}/store', 'TestController@store')->name('test.store');

            Route::resource('pregunta-desarrollo', 'PreguntaDesarrolloController');
            Route::get('/pregunta-desarrollo/{test}/index', 'PreguntaDesarrolloController@index')->name('pregunta-desarrollo.index');
            Route::post('/pregunta-desarrollo/{test}/store', 'PreguntaDesarrolloController@store')->name('pregunta-desarrollo.store');

            Route::resource('opcion-pregunta-desarrollo', 'OpcionPreguntaDesarrolloController');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/create', 'OpcionPreguntaDesarrolloController@create')->name('opcion-pregunta-desarrollo.create');
            Route::get('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/index', 'OpcionPreguntaDesarrolloController@index')->name('opcion-pregunta-desarrollo.index');
            Route::post('/opcion-pregunta-desarrollo/{pregunta_desarrollo}/store.imagen', 'OpcionPreguntaDesarrolloController@storeImagen')->name('opcion-pregunta-desarrollo.store.imagen');

app/Http/Controllers/Aplicacion/TareaController.php
<?php

namespace App\Http\Controllers\Aplicacion;

use App\Http\Controllers\Controller;
use App\Http\Requests\Tarea\StorePostCalificacion;
use App\Models\Desarrollo;
use App\Models\DesarrolloEstudiante;
use App\Models\Docente;
use App\Models\MaterialDocente;
use App\Models\MaterialEstudiante;
use App\Models\ParametroSubjetivo;
use App\Models\SegmentoLibro;
use App\Models\Tarea;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TareaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', 'acceso-app']);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $model = new Docente();
        $materialDocentes = MaterialDocente::obtenerMaterialDocenteUserAll(Auth::user()->id);
        return view('aplicacion.tareas.index', compact('materialDocentes', 'model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostCalificacion $request, MaterialEstudiante $materialEstudiante, Desarrollo $desarrollo)
    {
        $desarrolloEstudiante = DesarrolloEstudiante::getDesarrolloEstudianteMaterialEstudianteRespuestaDesarrollo();
        dd($materialEstudiante, $desarrollo, $request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function show(Tarea $tarea)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function edit(Tarea $tarea)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tarea $tarea)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tarea $tarea)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function calificar(MaterialDocente $materialDocente, SegmentoLibro $segmentoLibro = null)
    {
        if (!$segmentoLibro) {
            if ($segmentos = $materialDocente->libro->segmentoLibros ?? []) {
                $segmentoLibro = $segmentos[0];
            }
        }

        $materialEstudiantes = MaterialEstudiante::obtenerMaterialEstudianteMaterialDocente($materialDocente);
        return view('aplicacion.tareas.calificar.index', compact('materialDocente', 'segmentoLibro', 'materialEstudiantes'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function calificarTarea(MaterialDocente $materialDocente, Tarea $tarea)
    {
        $calificacion_minima = ($calificacion = ParametroSubjetivo::obtenerCalificacionMinima()) ? $calificacion->calificacion : 0;
        $calificacion_maxima = ($calificacion = ParametroSubjetivo::obtenerCalificacionMaxima()) ? $calificacion->calificacion : 0;

        $materialEstudiantes = MaterialEstudiante::obtenerMaterialEstudianteMaterialDocente($materialDocente);
        return view('aplicacion.tareas.calificar.tarea', compact('materialDocente', 'tarea', 'materialEstudiantes', 'calificacion_minima', 'calificacion_maxima'));
    }

}

app/Http/Controllers/TareaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tarea\StorePost;
use App\Http\Requests\Tarea\UpdatePut;
use App\Models\SegmentoLibro;
use App\Models\Tarea;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TareaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(SegmentoLibro $segmentoLibro)
    {
        $tarea = New Tarea();
        $tareas = Tarea::obtenerTareasSegmentoLibroAll($segmentoLibro->id);
        return view('backend.tarea.create', ['segmentoLibro' => $segmentoLibro, 'model' => $tarea, 'tareas' => $tareas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request, SegmentoLibro $segmentoLibro)
    {
        $requestData = $request->validated();
        $validator = Validator::make($requestData, StorePost::myRules());

        if ($validator->fails()) {
            return redirect('admin.abreviaturas.create')
                ->withErrors($validator)
                ->withInput();
        }

        $requestData['segmento_libro_id'] = $segmentoLibro->id;
        if ($model = Tarea::create($requestData)) {
            return back()->with('status', 'Tarea creada con exito');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function edit(Tarea $tarea)
    {
        $tareas = Tarea::obtenerTareasSegmentoLibroAll($tarea->segmento_libro_id);
        return view('backend.tarea.create', ['segmentoLibro' => $tarea->segmentoLibro, 'model' => $tarea, 'tareas' => $tareas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePut $request, Tarea $tarea)
    {
        $tarea->update($request->validated());
        return back()
            ->with('status', 'Tarea actualizada con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tarea $tarea
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tarea $tarea)
    {
        $tarea->delete();
        return back()->with('status','Tarea eliminada con exito.');
    }
}

resources/views/backend/tarea/_form.blade.php
@csrf
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col col-8 text-aqua">
                <h6 class="m-0 font-weight-bold">Tareas: {{$segmentoLibro->libro->titulo}}
                    / {{$segmentoLibro->unidad}}</h6>
            </div>
        </div>

    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="row">
                <div class="col col-12">
                    <label for="unidad" class="bmd-label-floating">Tipo desarrollo</label>
                    <select name="tipo_desarrollo_id" id="tipo_desarrollo_id" class="form-control select2"
                            data-ajax--url="{{route('api.tipo_desarrollo.select2')}}">
                        @if($model->tipo_desarrollo_id)
                            <option value="{{$model->tipo_desarrollo_id}}">{{$model->tipoDesarrollo->descripcion}}</option>
                        @endif
                    </select>

                    @error('tipo_desarrollo_id')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="col col-12 mt-2">
                    <label for="tipo_calificacion_id" class="bmd-label-floating">Tipo calificaci&oacute;n</label>
                    <select name="tipo_calificacion_id" id="tipo_calificacion_id"
                            data-ajax--url="{{route('api.tipo_calificacion.select2')}}"
                            class="form-control select2">
                        @if($model->tipo_calificacion_id)
                            <option value="{{$model->tipo_calificacion_id}}">{{$model->tipoCalificacion->descripcion}}</option>
                        @endif
                    </select>

                    @error('tipo_calificacion_id')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="col col-12 mt-2">
                    <label for="unidad" class="bmd-label-floating">Objetivo</label>
                    <textarea name="objetivo" id="objetivo" class="form-control ckeditor-content">
                        {{$model->objetivo}}
                    </textarea>

                    @error('objetivo')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            {{--<div class="row">--}}
                {{--<div class="col col-12 mt-2">--}}
                    {{--<label for="unidad" class="bmd-label-floating">Fecha Ejecuci&oacute;n</label>--}}
                    {{--<input type="text" class="form-control datepicker" value="{{old('fecha_ejecucion',$model->fecha_ejecucion)}}">--}}

                    {{--@error('tipo_calificacion_id')--}}
                    {{--<small class="text-danger">{{ $message }}</small>--}}
                    {{--@enderror--}}
                {{--</div>--}}
            {{--</div>--}}

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="form-label pl-0">Fecha ejecuci&oacute;n</label>
                        <div class="input-group-overlay">
                            <input class="form-control appended-form-control cs-date-picker cs-date-range" type="text"
                                   placeholder="Seleccionar fecha"
                                   data-datepicker-options='{"altInput": false, "altFormat": "Y-m-d", "dateFormat": "Y-m-d"}'
                                   data-linked-input="#return-date" name="fecha_ejecucion" id="fecha_ejecucion"
                                   value="{{old('fecha_ejecucion',$model->fecha_ejecucion)}}">

                            <div class="input-group-append-overlay">
                                <span class="input-group-text"><i class="fe-calendar"></i></span>
                            </div>
                        </div>
                        @error('fecha_ejecucion')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="form-label pl-0">Fecha terminaci&oacute;n</label>
                        <div class="input-group-overlay">
                            <input class="form-control appended-form-control cs-date-picker" type="text"
                                   placeholder="Seleccionar fecha"
                                   data-datepicker-options='{"altInput": true, "altFormat": "Y-m-d", "dateFormat": "Y-m-d"}'
                                   id="return-date" name="fecha_terminacion" value="{{old('fecha_fin',$model->fecha_terminacion)}}"
                                   required>
                            <div class="input-group-append-overlay">
                                <span class="input-group-text"><i class="fe-calendar"></i></span>
                            </div>
                        </div>
                        @error('fecha_terminacion')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
            </div>

            <input type="hidden" id="token" value="{{ csrf_token() }}">
            <input type="submit" value="Cargar" class="mt-3 btn btn-primary" id="cargar-libro">
        </div>
    </div>
</div>

resources/views/backend/tarea/create.blade.php
@extends('layouts.aplicacion.app')

@section('breadcrum')
    <div class="row ">
        <div class="col col-7">
            @if(!$model->id)
                <div class="alert alert-primary" role="alert">
                    Crear nueva tarea
                </div>
            @else
                <div class="alert alert-warning" role="alert">
                    Actualizar tarea #{{$model->id}}
                </div>
            @endif
        </div>
        <div class="col col-4">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.home')}}">Inicio</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.libro.index')}}">Libros</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{route('admin.segmento_libro.index',$segmentoLibro->libro_id)}}">
                            Unidades
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Tareas</li>
                </ol>
            </nav>
        </div>
        <div class="col col-1 text-center">
            <a class="btn btn-success btn-sm mt-2"
               href="{{ route('admin.tarea.index',$segmentoLibro->id) }}">
                <i class="fe-plus"></i>
            </a>
        </div>
    </div>
@endsection

@section('content')
    @include('includes.validation-error-admin')
    <div class="row">
        <div class="col col-12">
            <form id="form-archivo"
                  @if(!$model->id)
                  action="{{ route("admin.tarea.store",$segmentoLibro->id) }}"
                  @else
                  action="{{ route("admin.tarea.update",$model->id) }}"
                  @endif
                  method="POST"
                  enctype='multipart/form-data'>
                @if(!$model->id)
                    @method('POST')
                @else
                    @method('PUT')
                @endif

                @include('backend.tarea._form', compact('segmentoLibro','model'))
            </form>
        </div>
        <div class="col col-12">
            @include('backend.tarea.index', compact('tareas'))
        </div>
    </div>

    @include('includes.forms.modal-delete',['name_route'=>'admin.tarea.destroy'])

@endsection

@section('scripts')
    <script type="text/javascript">
        window.deleteModalAjax('deleteModal');
    </script>
@endsection

resources/views/backend/tarea/index.blade.php
<div class="card">
    <div class="card-header card-header-primary">
        <div class="row">
            <div class="col col-9">
                <h6 class="strong">Tareas Ingresadas</h6>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Objetivo</th>
                <th>Desarrollo</th>
                <th>Calificaci&oacute;n</th>
                <th>Ejecuci&oacute;n</th>
                <th>Terminaci&oacute;n</th>
                <th>
                    <small>Created_at</small>
                </th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            @foreach($tareas as $tarea)
                <tr>
                    <td class="w-25">{!! $tarea->objetivo !!}</td>
                    <td class="text-justify">{!! $tarea->tipoDesarrollo->descripcion !!}</td>
                    <td>{!! $tarea->tipoCalificacion->descripcion !!}</td>
                    <td>
                        <small>{{ \App\Helpers\Helper::formatDate($tarea->fecha_ejecucion) }}</small>
                    </td>
                    <td>
                        <small>{{ \App\Helpers\Helper::formatDate($tarea->fecha_terminacion) }}</small>
                    </td>
                    <td class="created_at">
                        <small>{{ $tarea->created_at->format('M d Y h:i') }}</small>
                    </td>
                    <td class="w-auto">
                        <a href="{{route('admin.desarrollo.index', $tarea->id)}}" class="nav-link-style mr-1"
                           data-toggle="tooltip"
                           data-placement="top" title="{{__('INGRESAR DESARROLLO')}}">
                            <i class="fas fa-tasks"></i>
                        </a>
                        <a href="{{route('admin.tarea.edit',$tarea->id)}}" class="nav-link-style mr-1"
                           data-toggle="tooltip" data-placement="top" title="{{__('EDITAR')}}">
                            <i class="fe-edit-2"></i>
                        </a>
                        <a data-toggle="modal" data-target="#deleteModal" data-id="{{ $tarea->id }}"
                           class="nav-link-style text-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="m-3">
            {{--{{--}}
            {{--$libros--}}
            {{--->appends(['created_at' => request('created_at'),'search' => request('search'),])--}}
            {{--->links()--}}
            {{--}}--}}
        </div>
    </div>
</div>

@include('includes.forms.modal-delete',['name_route'=>'admin.tarea.destroy'])

<script>
    // window.onload = function () {
    //     $('#deleteModal').on('show.bs.modal', function (event) {
    //         var button = $(event.relatedTarget); // Button that triggered the modal
    //         var id = button.data('id'); // Extract info from data-* attributes
    //         // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    //         // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    //
    //         action = $('#formDelete').attr('data-action').slice(0, -1);
    //         action += id;
    //         console.log(action);
    //
    //         $('#formDelete').attr('action', action);
    //
    //         var modal = $(this);
    //         modal.find('.modal-title').text('Borrar el Archivo: ' + id);
    //     });
    // };
</script>